Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Part c (b?)

def predict(x, coeff):
    return coeff[0] * x + coeff[1]

# Predictions for 2025 for both US and Europe using the least-squares regression model
predicted_US_2025_ls = predict(2025, coeff_US)
predicted_EURO_2025_ls = predict(2025, coeff_EURO)

print("Predicted 2025 US energy use: ",predicted_US_2025_ls)
print("Predicted 2025 EURO energy use: ",predicted_EUR_2025_ls)
------------------

----- stdout -----
Predicted 2025 US energy use:  29284.468724693055
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[21], line 11[0m
[1;32m      8[0m predicted_EURO_2025_ls [38;5;241m=[39m predict([38;5;241m2025[39m, coeff_EURO)
[1;32m     10[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mPredicted 2025 US energy use: [39m[38;5;124m"[39m,predicted_US_2025_ls)
[0;32m---> 11[0m [38;5;28mprint[39m([38;5;124m"[39m[38;5;124mPredicted 2025 EURO energy use: [39m[38;5;124m"[39m,[43mpredicted_EUR_2025_ls[49m)

[0;31mNameError[0m: name 'predicted_EUR_2025_ls' is not defined

