Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1305, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/asyncio/base_events.py", line 647, in run_until_complete
    return future.result()
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 705, in async_execute
    await self.async_execute_cell(
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 1058, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/opt/hostedtoolcache/Python/3.9.18/x64/lib/python3.9/site-packages/nbclient/client.py", line 914, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
#Part c

#Time setup for integration with the found dm_dt_root
time_to_burn = m0 / dm_dt_root
t = np.linspace(0, time_to_burn, 500)  # array of time values
dt = t[1] - t[0]  # time step

#Integrate the rocket equation over time with the found dm_dt_root
states = np.array([0, 0, m0])  # initial state vector [position, velocity, mass]
heights = []

for ti in t:
    derivatives = rocket(states, dmdt_root, u, c)
    states = states + derivatives * dt
    heights.append(states[0])

#Plotting
plt.figure(figsize=(10, 5))
plt.plot(t, heights, label='Height vs Time')
plt.plot(time_to_burn, height_desired, 'r*', label='Detonation Point')
plt.title('Rocket Height vs Time with Detonation Point')
plt.xlabel('Time (s)')
plt.ylabel('Height (m)')
plt.legend()
plt.show()
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[11], line 13[0m
[1;32m     10[0m heights [38;5;241m=[39m []
[1;32m     12[0m [38;5;28;01mfor[39;00m ti [38;5;129;01min[39;00m t:
[0;32m---> 13[0m     derivatives [38;5;241m=[39m rocket(states, [43mdmdt_root[49m, u, c)
[1;32m     14[0m     states [38;5;241m=[39m states [38;5;241m+[39m derivatives [38;5;241m*[39m dt
[1;32m     15[0m     heights[38;5;241m.[39mappend(states[[38;5;241m0[39m])

[0;31mNameError[0m: name 'dmdt_root' is not defined

